# Generated by Django 4.2.3 on 2024-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_course_studentprofile_sponsorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_facilitator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
