# Generated by Django 4.2.3 on 2024-01-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_customuser_is_facilitator_customuser_is_sponsor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitatorprofile',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
