# Generated by Django 4.2.3 on 2024-01-30 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_course_schedule_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_schedule',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.course'),
        ),
    ]
