# Generated by Django 4.2.3 on 2024-02-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_alter_course_options_alter_course_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
