# Generated by Django 4.2.3 on 2024-02-01 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_alter_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='course_schedule',
            name='facilitator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.facilitatorprofile'),
        ),
    ]
