# Generated by Django 4.2.3 on 2024-02-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_course_schedule_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_schedule',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_schedule',
            name='duration',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
