# Generated by Django 4.2.3 on 2024-02-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_studentprofile_purchased_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='purchased_courses',
            field=models.ManyToManyField(to='LMS.course'),
        ),
    ]
