# Generated by Django 4.2.3 on 2024-02-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_alter_studentprofile_purchased_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='purchased_courses',
        ),
    ]
