# Generated by Django 4.2.7 on 2024-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0016_studentprofile_purchased_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
