# Generated by Django 4.2.7 on 2024-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0017_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
