# Generated by Django 4.2.7 on 2024-03-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0020_rename_location_facilitatorprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='NIN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
