# Generated by Django 4.2.7 on 2024-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0021_studentprofile_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
