# Generated by Django 4.2.7 on 2024-03-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0023_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
