# Generated by Django 4.2.7 on 2024-03-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0026_studentprofile_course_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_schedule',
            old_name='course',
            new_name='course_title',
        ),
        migrations.AddField(
            model_name='course_schedule',
            name='course_of_study',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_schedule',
            name='link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
