# Generated by Django 4.2.7 on 2024-03-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0027_rename_course_course_schedule_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_schedule',
            name='course_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.course', unique=True),
        ),
    ]
