# Generated by Django 4.2.7 on 2024-03-31 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0029_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_schedule',
            name='course_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.course'),
        ),
    ]
