# Generated by Django 4.2.7 on 2024-04-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0030_alter_course_schedule_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(default='general', max_length=255, null=True),
        ),
    ]
