# Generated by Django 4.2.7 on 2024-04-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0032_course_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course_schedule',
        ),
    ]
