# Generated by Django 4.2.7 on 2024-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0033_remove_studentprofile_course_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course_schedule',
            field=models.ManyToManyField(blank=True, to='LMS.course_schedule'),
        ),
    ]
