# Generated by Django 4.2.7 on 2024-04-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0034_studentprofile_course_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_content',
            name='contents',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course_content',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
