# Generated by Django 4.2.7 on 2024-04-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0036_grant_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_schedule',
            name='course_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.course_content'),
        ),
    ]
