# Generated by Django 4.2.7 on 2024-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0038_course_schedule_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(default='General', max_length=255, null=True),
        ),
    ]
